### ISSUE TITLE
K-Pop selection button doesn't work in tray

### ISSUE THREAD

**Issue by ohlookitsderpy** [LISTEN-moe/desktop-app#15]
Upon starting the desktop app, the tray menu looks like this:<br> <img src='https://u.derpyenterprises.org/0d6e'>

When clicking on this, the check disappears but the radio isn't switched to K-Pop. I have tried this being logged in and logged out.

System Information:
LISTEN Version: latest release (iirc also on master)
OS Version: Windows 10 Home 1909

**Comment by robflop** [comment]
This was fixed in 9921bca and can be closed.

@Pitu
