### ISSUE TITLE
Improper name in media controls for Windows 10

### ISSUE THREAD

**Issue by kotx** [LISTEN-moe/desktop-app#20]
![image](https://user-images.githubusercontent.com/33439542/78314439-d1ea3300-750e-11ea-8067-1e2f31a172d6.png)

**Comment by Pitu** [comment]
Could you elaborate a bit further how to reproduce this?

**Comment by kotx** [comment]
Just try to change the volume or use pause using the function keys while the app is playing

**Comment by robflop** [comment]
This should be fixed with the latest commit. There's no release for it yet, though.
