### ISSUE TITLE
Suggestion : Use portable mpv + stream link

### ISSUE THREAD

**Issue by voltrare** [LISTEN-moe/desktop-app#36]
I am not that good about programming but
why not make the app based on

mpv https://listen.moe/stream

maybe this will make it lighter

![Screenshot_2020-08-09_21-34-35](https://user-images.githubusercontent.com/30526233/89733495-7580bc80-da88-11ea-97f7-73080295ca68.png)

**Comment by iCrawl** [comment]
And where would you presume the extra functionality like favoriting, switching the radio on the fly and the whole design comes from?

Playing the stream itself is not what makes it "big".

**Comment by voltrare** [comment]
thats true haha sorry for not thinking deep...

btw really love listen.moe
