### ISSUE TITLE
virus detected from windows defender

### ISSUE THREAD

**Issue by flolep2607** [LISTEN-moe/desktop-app#48]
![image](https://user-images.githubusercontent.com/24566964/124243362-19021200-db1e-11eb-805d-0248675de2c1.png)

**Comment by Pitu** [comment]
That's nonsense, here's a check from [VirusTotal](https://www.virustotal.com/gui/url/a23b419955e0a82be320106744f9dec9497c0c639c6050c9b50dcf033de3d469/detection)

**Comment by flolep2607** [comment]
ik but i get that's and i don't know why
